Header header

# This msg holds information of objects of intrest

# G-man
bool  gman_found 
int16 gman_object_x
int16 gman_object_y
int16 gman_object_z

# Bootlegger
bool  bootlegger_found 
int16 bootlegger_object_x
int16 bootlegger_object_y
int16 bootlegger_object_z

# Tommygun
bool  tommygun_found 
int16 tommygun_object_x
int16 tommygun_object_y
int16 tommygun_object_z

# Badge
bool  badge_found 
int16 badge_object_x
int16 badge_object_y
int16 badge_object_z

